// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: protocol/pricer.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest_Action int32

const (
	SubscribeRequest_ADD SubscribeRequest_Action = 0
	SubscribeRequest_DEL SubscribeRequest_Action = 1
)

// Enum value maps for SubscribeRequest_Action.
var (
	SubscribeRequest_Action_name = map[int32]string{
		0: "ADD",
		1: "DEL",
	}
	SubscribeRequest_Action_value = map[string]int32{
		"ADD": 0,
		"DEL": 1,
	}
)

func (x SubscribeRequest_Action) Enum() *SubscribeRequest_Action {
	p := new(SubscribeRequest_Action)
	*p = x
	return p
}

func (x SubscribeRequest_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscribeRequest_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_pricer_proto_enumTypes[0].Descriptor()
}

func (SubscribeRequest_Action) Type() protoreflect.EnumType {
	return &file_protocol_pricer_proto_enumTypes[0]
}

func (x SubscribeRequest_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscribeRequest_Action.Descriptor instead.
func (SubscribeRequest_Action) EnumDescriptor() ([]byte, []int) {
	return file_protocol_pricer_proto_rawDescGZIP(), []int{0, 0}
}

type SubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action  SubscribeRequest_Action `protobuf:"varint,1,opt,name=action,proto3,enum=pgrpc.SubscribeRequest_Action" json:"action,omitempty"`
	PriceId []int32                 `protobuf:"varint,2,rep,packed,name=price_id,json=priceId,proto3" json:"price_id,omitempty"`
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_pricer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_pricer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_protocol_pricer_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetAction() SubscribeRequest_Action {
	if x != nil {
		return x.Action
	}
	return SubscribeRequest_ADD
}

func (x *SubscribeRequest) GetPriceId() []int32 {
	if x != nil {
		return x.PriceId
	}
	return nil
}

type SubscribeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PriceId int32                  `protobuf:"varint,1,opt,name=price_id,json=priceId,proto3" json:"price_id,omitempty"`
	Bid     float32                `protobuf:"fixed32,2,opt,name=bid,proto3" json:"bid,omitempty"`
	Ask     float32                `protobuf:"fixed32,3,opt,name=ask,proto3" json:"ask,omitempty"`
	Update  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=update,proto3" json:"update,omitempty"`
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_pricer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_pricer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_protocol_pricer_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeResponse) GetPriceId() int32 {
	if x != nil {
		return x.PriceId
	}
	return 0
}

func (x *SubscribeResponse) GetBid() float32 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *SubscribeResponse) GetAsk() float32 {
	if x != nil {
		return x.Ask
	}
	return 0
}

func (x *SubscribeResponse) GetUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.Update
	}
	return nil
}

var File_protocol_pricer_proto protoreflect.FileDescriptor

var file_protocol_pricer_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x67, 0x72, 0x70, 0x63, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x81, 0x01, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x70, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x07,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x49, 0x64, 0x22, 0x1a, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x44, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x44, 0x45,
	0x4c, 0x10, 0x01, 0x22, 0x86, 0x01, 0x0a, 0x11, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x03, 0x62, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x73, 0x6b, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x03, 0x61, 0x73, 0x6b, 0x12, 0x32, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x32, 0x4e, 0x0a, 0x06,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x73, 0x12, 0x44, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x12, 0x17, 0x2e, 0x70, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x25, 0x5a, 0x23,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x68, 0x75, 0x63, 0x6b,
	0x79, 0x2d, 0x31, 0x2f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocol_pricer_proto_rawDescOnce sync.Once
	file_protocol_pricer_proto_rawDescData = file_protocol_pricer_proto_rawDesc
)

func file_protocol_pricer_proto_rawDescGZIP() []byte {
	file_protocol_pricer_proto_rawDescOnce.Do(func() {
		file_protocol_pricer_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_pricer_proto_rawDescData)
	})
	return file_protocol_pricer_proto_rawDescData
}

var file_protocol_pricer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protocol_pricer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protocol_pricer_proto_goTypes = []interface{}{
	(SubscribeRequest_Action)(0),  // 0: pgrpc.SubscribeRequest.Action
	(*SubscribeRequest)(nil),      // 1: pgrpc.SubscribeRequest
	(*SubscribeResponse)(nil),     // 2: pgrpc.SubscribeResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_protocol_pricer_proto_depIdxs = []int32{
	0, // 0: pgrpc.SubscribeRequest.action:type_name -> pgrpc.SubscribeRequest.Action
	3, // 1: pgrpc.SubscribeResponse.update:type_name -> google.protobuf.Timestamp
	1, // 2: pgrpc.Prices.Subscribe:input_type -> pgrpc.SubscribeRequest
	2, // 3: pgrpc.Prices.Subscribe:output_type -> pgrpc.SubscribeResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protocol_pricer_proto_init() }
func file_protocol_pricer_proto_init() {
	if File_protocol_pricer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocol_pricer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_pricer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_pricer_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_pricer_proto_goTypes,
		DependencyIndexes: file_protocol_pricer_proto_depIdxs,
		EnumInfos:         file_protocol_pricer_proto_enumTypes,
		MessageInfos:      file_protocol_pricer_proto_msgTypes,
	}.Build()
	File_protocol_pricer_proto = out.File
	file_protocol_pricer_proto_rawDesc = nil
	file_protocol_pricer_proto_goTypes = nil
	file_protocol_pricer_proto_depIdxs = nil
}
